name: Kom
version: 0.001
main: nativelevel.KoM
depend: [SimpleClans, MythicMobs]
commands:
    gm:
    ops:
    komq:
    pvpm:
    verexp:
    dislike:
    fechar:
    komlib:
    l:
    r:
    foguete:
    hat:
    dartitulo:
    gemas:
    limpamobs:
    gerador:
    setarbloco:
    teleportar:
    like:
    loot:
    ajudantes:
    ajuda:
    responder:
    pergunta:
    perguntas:
    anunciar:
    genero:
    titulo:
    setpreco:
    darxp:
    falar:
    reinicio:
    komx:
    lobby:
    terrenox:
    towers:
    f:
    spawn:
    customitem:
    recompensa:
    kompaste:
    consoleitem:
    voteshop:
    score:
    limpaitem:
    arena:
    doar:
    lobo:
    msgraio:
    tpraio:
    msgzinha: